name: Utils

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call 'Build' workflow
        uses: luos-io/utils/.github/worflow/build.yml@main

      - name: Publish
        run: yarn publish --access private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
