name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: luos-io/utils/.github/workflows/build.yml@main
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        run: yarn publish --access private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
